"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Repository = exports.Controller = exports.Service = void 0;
const component_1 = require("./component");
const Service = (options = {}) => (0, component_1.Component)({ ...options, type: "service" });
exports.Service = Service;
const Controller = (options = {}) => (0, component_1.Component)({ ...options, type: "controller" });
exports.Controller = Controller;
const Repository = (options = {}) => (0, component_1.Component)({ ...options, type: "repository" });
exports.Repository = Repository;
